# Generated by Django 5.2.12 on 2026-04-01 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ονοματεπώνυμο')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Θέμα')),
                ('message', models.TextField(verbose_name='Μήνυμα')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημ/νία')),
                ('notification_admin', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0, verbose_name='Κατάσταση')),
                ('unique', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
