# Generated by Django 5.2.12 on 2026-04-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Website', max_length=100, verbose_name='Όνομα Ιστοσελίδας')),
                ('site_name_sort', models.CharField(default='My Website Sort Name', max_length=100, verbose_name='Όνομα Ιστοσελίδας Sort')),
                ('description', models.TextField(blank=True, default='Καλώς ήρθατε στην ιστοσελίδα μας!', null=True, verbose_name='Περιγραφή')),
                ('main_image', models.ImageField(blank=True, help_text='Εικόνα hero ή banner', null=True, upload_to='sitefront/', verbose_name='Κύρια Εικόνα')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='sitefront/favicon/', verbose_name='Favicon')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com', null=True)),
                ('instagram', models.URLField(blank=True, default='https://instagram.com', null=True)),
                ('twitter', models.URLField(blank=True, default='https://twitter.com', null=True)),
                ('linkedin', models.URLField(blank=True, default='https://linkedin.com', null=True)),
                ('email', models.EmailField(blank=True, default='info@example.com', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='+30 210 1234567', max_length=20, null=True)),
                ('address', models.CharField(blank=True, default='Αθήνα, Ελλάδα', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ρύθμιση Ιστοσελίδας',
                'verbose_name_plural': 'Ρυθμίσεις Ιστοσελίδας',
            },
        ),
    ]
