# Generated by Django 5.2.12 on 2026-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('courses', '0002_lessonmodule_alter_lesson_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='lesson_modules',
            field=models.ManyToManyField(blank=True, related_name='author_profiles', to='courses.lessonmodule', verbose_name='Ενότητες μαθημάτων'),
        ),
    ]
