# Generated by Django 5.2.12 on 2026-04-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonmodule_alter_lesson_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('true_false', 'Σωστό / Λάθος'), ('single', 'Checkbox'), ('multiple', 'Πολλαπλής επιλογής')], max_length=20),
        ),
    ]
