# Generated by Django 5.2.12 on 2026-04-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='lessonmodule',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_modules/'),
        ),
        migrations.AlterField(
            model_name='theorysection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='theory_sections/'),
        ),
    ]
