# Generated by Django 5.2.12 on 2026-05-14 21:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_userlessonsectionprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorysection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Περιεχόμενο'),
        ),
    ]
